Repository Hongmoon-gak/Job1-Web, pull requests merged in 2023-07, with the labels that each got.

#2 [FEAT] 로그인 버튼, navbar 레이아웃 구현
  job1/src/App.js
  job1/src/Main/NavBar.css
  job1/src/Main/NavBar.js
  job1/src/Main/NavItems.js
  job1/src/Main/NavUser.js
Labels: question, 재혁, FEAT, UI

#9 [FEAT] 게시판 미리보기 구현 (#7)
  job1/package-lock.json
  job1/package.json
  job1/public/index.html
  job1/src/App.js
  job1/src/Main/PrevArt.js
  job1/src/Main/PrevCont.js
  job1/src/Main/Preview.css
  job1/src/Main/Preview.js
  job1/src/View/Home.js
  job1/src/View/Write.js
  package-lock.json
Labels: 주원, FEAT, UI

#6 [FEAT] Footer 구현 (#5)
  job1/src/App.js
  job1/src/Main/Footer.js
Labels: 재혁, FEAT, UI

#4 [FEAT] MoreInfo proto (#3)
  job1/src/Component/InfoCard.js
  job1/src/Main/MoreInfo.js
  job1/src/View/Home.js
Labels: 재혁, FEAT, UI

#12 [STYLE] 로고 및 CSS 작업 (#1)
  job1/src/Main/NavBar/NavBar.css
  job1/src/Main/NavBar/NavBar.js
Labels: 재혁, UI

#13 [FEAT] 검색바 구현 (#11)
  job1/src/Component/DataSample.js
  job1/src/Component/SearchBar.css
  job1/src/Component/SearchBar.js
  job1/src/Component/TestCp.js
  job1/src/Image/Search.png
  job1/src/View/Search.js
Labels: 재혁, FEAT, UI

#18 [FIX] 저작권자 수정 (#5)
  job1/src/Main/Footer.js
Labels: 재혁

#20 [FEAT] Card 외부 링크 연결 (#3)
  job1/src/Component/InfoCard.js
  job1/src/Main/MoreInfo.js
Labels: 재혁, FEAT, UI

#19 [FEAT] 쿼리 전달 및 뷰 전환 구현(#11)
  job1/src/Component/SearchBar.js
Labels: 재혁, FEAT

#21 [FIX] view 컴포넌트 재수정 (#16)
  job1/src/App.js
  job1/src/Tags/Tag.js
  job1/src/View/Board.js
  job1/src/View/Home.js
  job1/src/View/Laws.js
  job1/src/View/News.js
  job1/src/View/Search.js
Labels: 재혁, UI, FIX

#22 [FIX] main 폴더 중복 파일 삭제
  job1/src/Main/NavBar.css
  job1/src/Main/NavBar.js
  job1/src/Main/NavItems.js
  job1/src/Main/NavUser.js
  job1/src/Main/PrevArt.js
  job1/src/Main/PrevCont.js
  job1/src/Main/Preview.css
  job1/src/Main/Preview.js
Labels: 주원, FIX

#23 [STYLE] navMenu 선택 여부 보이기 (#1)
  job1/src/Main/NavBar/NavBar.css
  job1/src/Main/NavBar/NavBar.js
Labels: 재혁, UI

#25 Feature/preview/search
  job1/public/Images/CommunityLike.png
  job1/src/App.js
  job1/src/Main/Preview/DataSample.js
  job1/src/Main/Preview/PrevArt.js
  job1/src/Main/Preview/PrevCont.js
  job1/src/Main/Preview/Preview.css
  job1/src/Main/Preview/Preview.js
  job1/src/View/Home.js
  job1/src/View/SearchResult.js
Labels: 주원, FEAT

#27 [ADD] 로그인 기능, 임시 로딩 화면, 백에게 인가 코드 전달 구현
  .gitignore
  job1/package-lock.json
  job1/package.json
  job1/public/Images/kakao_login.png
  job1/src/App.js
  job1/src/Component/Tag.js
  job1/src/View/Login.js
  job1/src/View/Login/Login.js
  job1/src/View/Login/LoginComponent.js
  job1/src/View/Login/LoginHandler.js
  job1/src/View/Search.js
Labels: 승용, FEAT
